name: Two-Job Workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      first_output: ${{ steps.set_output.outputs.first_number }}
      second_output: ${{ steps.set_output.outputs.second_number }}
    steps:
      - name: Checkout
        uses: actions/checkout
      - name: Set Outputs
        id: set_output
        run: |
          echo "first_number=7" >> $GITHUB_ENV
          echo "second_number=3" >> $GITHUB_ENV

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sum Outputs
        run: |
          sum=$((${{ needs.job1.outputs.first_output }} + ${{ needs.job1.outputs.second_output }}))
          echo "Sum is $sum"
