name: Greeting on variable day
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  workflow_dispatch
env:
  DAY_OF_WEEK: Monday
 
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:    
      Greeting: Hello
      First_Name : SHRAVAN
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"  
